# apiVersion: v1
# kind: Service
# metadata:
#   name: nexus
# spec:
#   selector: 
#     app: nexus-server
#   type: ClusterIP  
#   ports:
#     - name: http
#       port: 8081
#       protocol: TCP
#       targetPort: 8081