# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: reloader
# resources:
# - namespace.yaml
# - helmsync.yaml
# - helmrelease.yaml
# - rbac.yaml
# - network-policies.yaml
