apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- namespace.yaml
- helmsync.yaml
- helmrelease.yaml
- rbac.yaml
- secrets.yaml
- network-policies.yaml
