apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tf-controller
resources:
  - namespace.yaml
  - helmrelease.yaml
  - helmsync.yaml
  - network-policies.yaml
  - rbac.yaml
  - ghcr-image-pull-secret.yaml